--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023. 03. 07. 0:13:11
-- Server version: 5.5.5-10.4.24-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS fifa;

CREATE DATABASE IF NOT EXISTS fifa
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE fifa;

--
-- Create table `posts`
--
CREATE TABLE IF NOT EXISTS posts (
  id INT(11) NOT NULL AUTO_INCREMENT,
  Positions VARCHAR(3) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 18,
AVG_ROW_LENGTH = 963,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `players`
--
CREATE TABLE IF NOT EXISTS players (
  id INT(11) NOT NULL AUTO_INCREMENT,
  Rating VARCHAR(2) NOT NULL,
  posID INT(2) NOT NULL,
  Nationality VARCHAR(5) NOT NULL,
  Club VARCHAR(30) NOT NULL,
  Name VARCHAR(50) NOT NULL,
  PAC INT(2) NOT NULL,
  SHO INT(2) NOT NULL,
  PAS INT(2) NOT NULL,
  DRI INT(2) NOT NULL,
  DEF INT(2) NOT NULL,
  PHY INT(2) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE players 
  ADD CONSTRAINT FK_players_posts_id FOREIGN KEY (posID)
    REFERENCES posts(id);

-- 
-- Dumping data for table posts
--
INSERT INTO posts VALUES
(1, 'GK'),
(2, 'CB'),
(3, 'RB'),
(4, 'LB'),
(5, 'RWB'),
(6, 'LWB'),
(7, 'CM'),
(8, 'CDM'),
(9, 'CAM'),
(10, 'RM'),
(11, 'LM'),
(12, 'ST'),
(13, 'CF'),
(14, 'RF'),
(15, 'LF'),
(16, 'RW'),
(17, 'LW');

-- 
-- Dumping data for table players
--
INSERT INTO players VALUES
(7, '93', 13, 'HUN', 'ICON', 'PUSKÁS', 91, 96, 91, 92, 46, 76),
(8, '84', 10, 'HUN', 'RB Leipzeg', 'SZOBOSZLAI', 83, 85, 86, 86, 40, 70);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;